/** fieldHint strings for fleet asset forms (Title\n\nBody). */
export const FLEET_ASSET_FIELD_HINTS = {
  asset_type: 'Asset Type\n\nVehicle, heavy machinery, or other fleet asset category.',
  name: 'Name\n\nDisplay name shown in lists and search results.',
  make: 'Make\n\nManufacturer or brand.',
  model: 'Model\n\nModel name or number.',
  year: 'Year\n\nModel year when applicable.',
  vin: 'VIN / Serial\n\nVehicle identification number or equipment serial.',
  license_plate: 'License Plate\n\nRegistered plate number for vehicles.',
  license: 'License\n\nLicense or registration identifier for this asset.',
  unit_number: 'Unit Number\n\nInternal unit or fleet number.',
  vehicle_type: 'Vehicle Type\n\nBody or class (e.g. SUV, pickup, van).',
  fuel_type: 'Fuel Type\n\nFuel or power source (e.g. diesel, gasoline, electric).',
  equipment_type_label: 'Type\n\nEquipment category label for heavy machinery or other assets.',
  condition: 'Condition\n\nPhysical condition rating.',
  status: 'Status\n\nOperational status in the fleet system.',
  icbc_registration_no: 'ICBC Registration No.\n\nBritish Columbia vehicle registration number.',
  vancouver_decals: 'Vancouver Decal #\n\nCity decal numbers; separate multiple values with commas.',
  ferry_length: 'Ferry Length\n\nFerry permit length notation (e.g. 22L 8H).',
  gvw_kg: 'GVW (kg)\n\nGross vehicle weight in kilograms.',
  gvw_value: 'GVW Value\n\nGross vehicle weight numeric value.',
  gvw_unit: 'GVW Unit\n\nUnit for GVW value (kg or lbs).',
  propane_sticker_cert: 'Propane Sticker Cert\n\nPropane certification or sticker reference number.',
  propane_sticker_date: 'Propane Sticker Date\n\nExpiry or issue date for the propane sticker.',
  yard_location: 'Sleeps\n\nDefault sleeps / yard location for this asset when not assigned.',
  odometer_current: 'Current Odometer\n\nLatest odometer reading for this vehicle.',
  odometer_last_service: 'Last Service Odometer\n\nOdometer reading at the last scheduled service.',
  odometer_next_due_at: 'Odometer Next Due At\n\nOdometer reading when the next service is due.',
  odometer_noted_issues: 'Odometer Noted Issues\n\nMaintenance notes tied to odometer readings.',
  hours_current: 'Current Hours\n\nLatest hour meter reading for this equipment.',
  hours_last_service: 'Last Service Hours\n\nHour meter reading at the last scheduled service.',
  hours_next_due_at: 'Hours Next Due At\n\nHour meter reading when the next service is due.',
  hours_noted_issues: 'Hours Noted Issues\n\nMaintenance notes tied to hour meter readings.',
  notes: 'Notes\n\nInternal notes about this asset; not shown on customer-facing documents.',
} as const;
