import DOMPurify from 'dompurify';
import type { Config } from 'dompurify';

/** Outlook / inbound email HTML — allow tables & inline styles, block active content. */
const INBOUND_EMAIL_SANITIZE: Config = {
  ALLOWED_TAGS: [
    'p',
    'br',
    'div',
    'span',
    'strong',
    'b',
    'em',
    'i',
    'u',
    's',
    'strike',
    'a',
    'img',
    'hr',
    'ul',
    'ol',
    'li',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'table',
    'thead',
    'tbody',
    'tfoot',
    'tr',
    'td',
    'th',
    'caption',
    'blockquote',
    'pre',
    'code',
    'font',
    'center',
  ],
  ALLOWED_ATTR: [
    'href',
    'src',
    'alt',
    'title',
    'class',
    'style',
    'width',
    'height',
    'align',
    'valign',
    'border',
    'cellpadding',
    'cellspacing',
    'colspan',
    'rowspan',
    'bgcolor',
    'color',
    'face',
    'size',
    'target',
    'rel',
  ],
  ALLOW_DATA_ATTR: false,
  ALLOWED_URI_REGEXP: /^(?:(?:https?|mailto|cid):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i,
};

export function sanitizeInboundEmailHtml(html: string): string {
  return DOMPurify.sanitize(html || '', INBOUND_EMAIL_SANITIZE);
}
