/** Field hints for employee profile edit modals (`fieldHint` / `AppFieldHint`). */
export const USER_PROFILE_FIELD_HINTS: Record<string, string> = {
  first_name: 'First name\n\nGiven name on file for reports, badges, and HR.',
  last_name: 'Last name\n\nFamily name on file for reports, badges, and HR.',
  middle_name: 'Middle name\n\nOptional middle name or initial.',
  preferred_name: 'Preferred name\n\nShown on the profile hero when set; overrides the composed legal name.',
  gender: 'Gender\n\nOptional; used for HR and reporting only.',
  marital_status: 'Marital status\n\nOptional demographic field for HR records.',
  date_of_birth: 'Date of birth\n\nUsed for age calculations and eligibility checks.',
  nationality: 'Nationality\n\nCountry of citizenship or nationality on file.',
  cloth_size: 'Cloth size\n\nUniform or PPE sizing for ordering gear.',
  address_line1: 'Address line 1\n\nStreet address. Suggestions appear as you type.',
  address_line2: 'Address line 2\n\nSuite, unit, or building (optional).',
  postal_code: 'Postal code\n\nZIP or postal code for mailing.',
  city: 'City\n\nFilled automatically when you pick an address suggestion.',
  province: 'Province/State\n\nProvince or state for mailing and payroll.',
  country: 'Country\n\nCountry for the mailing address.',
  phone: 'Phone 1\n\nPrimary personal phone number.',
  mobile_phone: 'Phone 2\n\nSecondary mobile or alternate number.',
  sin_number: 'SIN Number\n\nSocial Insurance Number (format NNN-NNN-NNN). Handle securely.',
  work_eligibility_status:
    'Work eligibility status\n\nWhether this person may work in Canada; drives visa and document requirements.',
  job_title: 'Job title\n\nRole or position title shown on the profile and org chart.',
  employment_type: 'Employment type\n\nFull-time, hourly, part-time, or salary classification.',
  manager_user_id: 'Supervisor\n\nReports-to manager for approvals and org structure.',
  hire_date: 'Hire date\n\nStart date of employment; used for tenure.',
  termination_date: 'Termination date\n\nLast day of employment, if applicable.',
  work_email: 'Work email\n\nCompany email for notifications and system access.',
  work_phone: 'Work phone\n\nCompany phone or desk line.',
  departments: 'Departments\n\nInternal divisions this employee belongs to.',
  project_division_ids: 'Project divisions\n\nProject lines or branches they work on.',
  pay_rate: 'Pay rate\n\nCurrent compensation amount (e.g. $29.00 / Hour).',
  pay_type: 'Pay type\n\nHow pay is structured: hourly, salary, contract, etc.',
  salary_effective_date: 'Effective date\n\nWhen the new pay rate takes effect; stored as the first day of the selected date.',
  salary_justification: 'Change reason\n\nRequired explanation for the salary change (e.g. promotion, annual review, market adjustment).',
  salary_notes: 'Comment\n\nOptional internal notes about this salary entry.',
  time_off_policy: 'Policy\n\nWhich time-off balance to adjust (e.g. Sick Leave or Vacation).',
  time_off_adjustment_amount:
    'Amount\n\nChoose Add or Subtract, then enter days (decimals such as 0.5 allowed).',
  time_off_effective_date:
    'Effective date\n\nWhen the balance change takes effect; appears in the employee time-off history.',
  time_off_adjustment_note:
    'Note\n\nRequired reason for the manual adjustment (e.g. carry-over correction, payroll sync).',
  drivers_license_number: "Licence number\n\nAs printed on the card.",
  drivers_license_jurisdiction: 'Province / territory\n\nIssuing province or territory.',
  drivers_license_class: 'Class / level\n\ne.g. G, Class 5.',
  drivers_license_issue_date: 'Issue date\n\nDate the licence was issued.',
  drivers_license_expiry_date: 'Expiry date\n\nUsed for expired / expiring-soon status on the card.',
  drivers_license_conditions: 'Conditions\n\nOptional restrictions (e.g. corrective lenses).',
  college_institution: 'Institution\n\nSchool, college, or university name.',
  degree: 'Degree\n\nDegree, diploma, or certification earned.',
  education_start: 'Start date\n\nWhen studies began; the first day of the selected month is stored.',
  education_end: 'End date\n\nWhen studies ended or are expected to end; the first day of the selected month is stored.',
  visa_type: 'Visa type\n\ne.g. Work Permit, Study Permit, or Open Work Permit.',
  visa_number: 'Visa number\n\nDocument or permit number as printed on the visa.',
  visa_issuing_country: 'Issuing country\n\nCountry that issued the visa or work authorization.',
  visa_issued_date: 'Issued date\n\nDate the visa or permit was issued.',
  visa_expiry_date: 'Expiry date\n\nDate the visa or permit expires; used for status on the profile.',
  visa_status: 'Status\n\nCurrent, expired, or pending — shown on the employee profile.',
  visa_notes: 'Notes\n\nOptional details such as LMIA number, occupation, or restrictions.',
  emergency_name: 'Name\n\nFull name of the emergency contact.',
  emergency_relationship: 'Relationship\n\ne.g. Spouse, parent, or friend.',
  emergency_mobile_phone: 'Mobile phone\n\nPrimary number to reach this contact.',
  emergency_home_phone: 'Home phone\n\nOptional home line.',
  emergency_work_phone: 'Work phone\n\nOptional work line.',
  emergency_email: 'Email\n\nEmail address for the emergency contact.',
  emergency_address: 'Address\n\nMailing or home address for this contact.',
};

export function userProfileFieldHint(key: string): string | undefined {
  return USER_PROFILE_FIELD_HINTS[key];
}
