/** Field hints for warranty form modals (AppFieldHint / ? tooltips). */
export const WARRANTY_FIELD_HINTS = {
  name: 'Name\n\nA clear label for this warranty record, e.g. Manufacturer Roof System Warranty.',
  warranty_type: 'Warranty type\n\nWorkmanship, manufacturer, material, subcontractor, extended, or other.',
  provider_type: 'Provider type\n\nWho issued or backs this warranty.',
  provider_name: 'Provider name\n\nCompany or party name when not selected from a supplier or subcontractor list.',
  status: 'Status\n\nDraft warranties can be saved before documents or registration are complete.',
  coverage_description: 'Coverage\n\nDescribe what this warranty covers on the project.',
  period_definition: 'Period definition\n\nChoose By duration to enter a term from the start date, or By end date to set the coverage end manually.',
  start_date: 'Start date\n\nWhen coverage begins. Can be derived from project completion when applicable.',
  end_date: 'End date\n\nWhen coverage ends. Use this when defining the period by a specific end date.',
  duration_value: 'Duration\n\nLength of coverage from the start date.',
  duration_unit: 'Duration unit\n\nDays, months, or years.',
  maintenance_required: 'Maintenance required\n\nWhen enabled, set how often maintenance is due and the next due date. The system tracks due dates and sends alerts.',
  maintenance_frequency: 'Frequency\n\nHow often required maintenance must be performed to keep the warranty valid.',
  maintenance_interval_value: 'Custom interval\n\nNumber of days, months, or years between required maintenance visits.',
  maintenance_interval_unit: 'Interval unit\n\nDays, months, or years for a custom maintenance schedule.',
  maintenance_due_date: 'Maintenance due date\n\nWhen the next required maintenance is due. Used for summary cards and alerts.',
  notes: 'Notes\n\nInternal notes about this warranty.',
  claim_warranty: 'Related warranty\n\nOptional link to the warranty this claim is filed under.',
  claim_description: 'Description\n\nDescribe the issue reported under warranty.',
  claim_severity: 'Severity\n\nEmergency claims notify the project admin immediately.',
  claim_issue_location: 'Issue location\n\nWhere on the site or building the problem was observed.',
  claim_reported_date: 'Reported date\n\nWhen the issue was first reported.',
} as const;
